# Generated by Django 5.2.1 on 2025-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_country_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
