# Generated by Django 5.2.1 on 2025-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0003_vacation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='image',
            field=models.ImageField(blank=True, upload_to='vacation_images/'),
        ),
    ]
