# Generated by Django 5.2.1 on 2025-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_vacationlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationbooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacationbooking',
            name='room_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Double'), (4, 'Family')], null=True),
        ),
        migrations.AlterField(
            model_name='vacationbooking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
