# Generated by Django 5.2.1 on 2025-06-26 17:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0009_alter_vacation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
            preserve_default=False,
        ),
    ]
